server:
  port: 8080
  

  
spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
   
  datasource:
    url: jdbc:h2:mem:statestreetdb
    driver-class-name: org.h2.Driver
    username: sa
    password:  
    
  flyway:
    enabled: true